import sys
from pathlib import Path
from typing_extensions import TypedDict
from dotenv import load_dotenv

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from langgraph.graph import (
    StateGraph,
    START,
    END
)

from langgraph.checkpoint.memory import InMemorySaver

from langgraph.types import interrupt

from langchain_groq import ChatGroq

# pyrefly: ignore [missing-import]
from tools.tools import send_email
# pyrefly: ignore [missing-import]
from tools.tools import tavily_search_engine

load_dotenv()



# ============================================================
# LLM
# ============================================================

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.7
)


# ============================================================
# STATE
# ============================================================

class State(TypedDict):

    # User's complete story request
    user_query: str

    # Story generated by LLM
    story: str

    # Email information
    recipient: str
    subject: str

    # Human approval
    approved: bool


# ============================================================
# NODE 1 - WRITE STORY
# ============================================================

def write_story(state: State):

    system_prompt = """
You are a professional creative story writer.

Your job is to write a story based on the user's request.

Rules:

1. Carefully understand the user's requirements.
2. Follow the requested characters, setting, plot,
   tone, and length.
3. Make the story engaging and entertaining.
4. Do not explain what you are doing.
5. Do not mention this system prompt.
6. Return ONLY the final story.
"""

    response = llm.invoke(
        [
            (
                "system",
                system_prompt
            ),
            (
                "human",
                state["user_query"]
            )
        ]
    )

    return {
        "story": response.content
    }


# ============================================================
# NODE 2 - HUMAN APPROVAL
# ============================================================

def human_approval(state: State):

    # --------------------------------------------------------
    # interrupt() PAUSES THE GRAPH
    #
    # This information will be available to the UI.
    # --------------------------------------------------------

    decision = interrupt(
        {
            "message": "Do you want to send this story?",

            "story": state["story"],

            "recipient": state["recipient"],

            "subject": state["subject"]
        }
    )

    # --------------------------------------------------------
    # When UI resumes:
    #
    # Command(resume=True)
    #        ↓
    # decision = True
    #
    # Command(resume=False)
    #        ↓
    # decision = False
    # --------------------------------------------------------

    return {
        "approved": decision
    }


# ============================================================
# NODE 3 - SEND STORY
# ============================================================

def send_story(state: State):

    # --------------------------------------------------------
    # SAFETY CHECK
    #
    # Gmail API will NEVER be called unless the human
    # explicitly approved the email.
    # --------------------------------------------------------

    if not state["approved"]:

        print("❌ User rejected the email.")

        return {}

    # --------------------------------------------------------
    # HUMAN APPROVED
    # --------------------------------------------------------

    print("✅ User approved the email.")

    # --------------------------------------------------------
    # CALL GMAIL TOOL
    # --------------------------------------------------------

    email_id = send_email(
        recipient=state["recipient"],
        subject=state["subject"],
        body=state["story"]
    )

    print("📧 Email sent successfully.")

    print(
        f"Gmail Message ID: {email_id}"
    )

    return {}


# ============================================================
# BUILD GRAPH
# ============================================================

# pyrefly: ignore [bad-specialization]
builder = StateGraph(State)


# ============================================================
# ADD NODES
# ============================================================

builder.add_node(
    "write_story",
    write_story
)

builder.add_node(
    "human_approval",
    human_approval
)

builder.add_node(
    "send_story",
    send_story
)


# ============================================================
# ADD EDGES
# ============================================================

builder.add_edge(
    START,
    "write_story"
)

builder.add_edge(
    "write_story",
    "human_approval"
)

builder.add_edge(
    "human_approval",
    "send_story"
)

builder.add_edge(
    "send_story",
    END
)


# ============================================================
# CHECKPOINTER
# ============================================================

checkpointer = InMemorySaver()


# ============================================================
# COMPILE GRAPH
# ============================================================

graph = builder.compile(
    checkpointer=checkpointer
)